apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 3Gi
    storageClass: "storageclass-postgresql"
  numberOfInstances: 2
  postgresql:
    version: "15"
