apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "product-3shard-1repl"
spec:
  configuration:
    users:
      default/password_sha256_hex: 9a6444956bcdc320ae0d6aef32c8c28fa00fab0b713b10247d74e3b96a8e6a79
      admin/k8s_secret_password_sha256_hex: clickhouse-secret/admin
      admin/networks/host_regexp: ".*"
      admin/networks/ip:
        - "0.0.0.0/0"
        - "::/0"
    zookeeper:
      nodes:
        - host: zookeeper.zoons.svc.cluster.local
          port: 2181
    clusters:
      - name: default
        secret:
          auto: "true"
        templates:
          podTemplate: pod-template-with-volumes
        layout:
          shardsCount: 3
          replicasCount: 1

  templates:
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          containers:
            - name: clickhouse
              image: "clickhouse/clickhouse-server:22.3"
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server

    volumeClaimTemplates:
      - name: data-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: storageclass-clickhouse
      - name: log-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: storageclass-clickhouse
