# Specify StorageClass in case there is no default storage class provided

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-redis
provisioner: k8s.io/minikube-hostpath
# Choose desired 'volumeBindingMode'
#volumeBindingMode: WaitForFirstConsumer
volumeBindingMode: Immediate
